server:
  port: 8881
  ssl:
    protocol: TLS
    key-store: classpath:.keystore
    key-store-password: 123456
    key-store-type: JKS


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test


logging:
  level:
    com.example: debug
  console:
    enabled: true
